import moxibustionImage from "@/assets/external-therapies/moxibustion.jpg";
import tuinaImage from "@/assets/external-therapies/tuina.jpg";
import cuppingImage from "@/assets/external-therapies/cupping.jpg";
import guaShaImage from "@/assets/external-therapies/gua-sha.jpg";
import herbalApplicationImage from "@/assets/external-therapies/herbal-application.jpg";
import fumigationImage from "@/assets/external-therapies/fumigation.jpg";
import herbalBathImage from "@/assets/external-therapies/herbal-bath.jpg";
import auricularImage from "@/assets/external-therapies/auricular.jpg";
import aromatherapyImage from "@/assets/external-therapies/aromatherapy.jpg";
import movementImage from "@/assets/external-therapies/movement.jpg";
import dietaryTherapyImage from "@/assets/external-therapies/dietary-therapy.jpg";

export type LocalizedTherapyCopy = {
  name: string;
  description: string[];
  highlights?: Array<{ title: string; description: string }>;
};

export type ExternalTherapy = {
  id: string;
  image: string;
  zh: LocalizedTherapyCopy;
  en: LocalizedTherapyCopy;
};

export const externalTherapies: ExternalTherapy[] = [
  {
    id: "moxibustion",
    image: moxibustionImage,
    zh: { name: "艾灸", description: ["艾灸是利用艾叶制成的艾绒燃烧所产生的温热作用，刺激人体穴位或特定部位的一种传统外治方法。中医认为艾灸具有温经散寒、通络调气、扶助阳气等作用，常用于日常保健以及寒凉、虚弱等体质的调理。"] },
    en: { name: "Moxibustion", description: ["Moxibustion is a traditional Chinese medicine therapy that uses the gentle heat generated by burning processed mugwort (moxa) near selected acupoints or areas of the body. In traditional Chinese medicine, moxibustion is used to warm the body, support the flow of Qi and Blood, and promote circulation through the meridians. It is commonly used as part of wellness and supportive care, particularly for people who are sensitive to cold or tend to feel physically depleted."] },
  },
  {
    id: "tuina",
    image: tuinaImage,
    zh: { name: "推拿", description: ["推拿是以手法作用于肌肉、筋膜、经络和穴位的传统中医外治方法，包括推、拿、按、揉、摩、擦、滚等多种手法。通过适当的手法刺激，可以帮助放松肌肉、舒展筋脉、调畅气血，并促进身体的整体平衡。"] },
    en: { name: "Tuina / Chinese Therapeutic Massage", description: ["Tuina is a traditional Chinese manual therapy using techniques such as pressing, kneading, rolling, rubbing and stretching. It works on muscles, soft tissues, acupoints and meridian pathways. Tuina is traditionally used to release muscular tension, support circulation and mobility, and promote relaxation and physical balance."] },
  },
  {
    id: "cupping",
    image: cuppingImage,
    zh: { name: "拔罐", description: ["拔罐是通过罐具在皮肤表面形成负压，使罐体吸附于身体特定部位的一种传统外治方法。中医认为拔罐可以帮助疏通经络、行气活血、祛除寒湿，并常用于肌肉紧张和身体不适的调理。"] },
    en: { name: "Cupping", description: ["Cupping is a traditional therapy in which specially designed cups are placed on the skin to create gentle suction. In traditional Chinese medicine, cupping is used to stimulate the tissues, support the movement of Qi and Blood, and promote relaxation of muscles and soft tissues. It is commonly incorporated into wellness and supportive bodywork practices."] },
  },
  {
    id: "gua-sha",
    image: guaShaImage,
    zh: { name: "刮痧", description: ["刮痧是使用刮痧板等光滑工具，在皮肤表面进行特定方向的刮拭和刺激。中医认为刮痧可以疏通经络、调畅气血、帮助身体恢复平衡。刮痧后皮肤可能出现暂时性的红色或紫红色痧象，这是常见的反应。"] },
    en: { name: "Gua Sha", description: ["Gua Sha is a traditional Chinese technique that uses a smooth-edged tool to apply controlled strokes to the skin. Traditionally, it is used to stimulate circulation, support the flow of Qi and Blood, and promote relaxation and balance. Temporary redness or purple-red marks may appear after treatment and generally fade as the skin recovers."] },
  },
  {
    id: "herbal-application",
    image: herbalApplicationImage,
    zh: { name: "外敷", description: ["中药外敷是将适当的中药制成膏、散、糊、药饼等形式，应用于身体特定部位或穴位。药物与局部刺激相结合，是中医“内病外治”的重要方法之一，可根据不同情况进行个体化选择。"] },
    en: { name: "External Herbal Application", description: ["External herbal application involves applying appropriately prepared Chinese herbal medicines to specific areas of the body or selected acupoints. Herbs may be prepared as pastes, powders, herbal packs or other topical preparations. It is an important traditional approach in Chinese medicine and may be selected according to an individual's constitution and health needs."] },
  },
  {
    id: "fumigation",
    image: fumigationImage,
    zh: { name: "熏蒸", description: ["中药熏蒸是利用中药煎煮产生的温热蒸汽，使药物气味和温热作用作用于身体表面。中医认为熏蒸可以温通经络、舒缓肌肉，并帮助身体放松。可根据需要进行全身或局部熏蒸。"] },
    en: { name: "Herbal Fumigation & Steam Therapy", description: ["Herbal fumigation and steam therapy use warm steam generated from selected Chinese herbs to gently expose the body to heat and aromatic herbal vapours. Traditionally, this approach is used to warm and relax the body, support circulation and ease muscular tension. It may be applied to the whole body or to specific areas."] },
  },
  {
    id: "herbal-bath",
    image: herbalBathImage,
    zh: { name: "药浴", description: ["药浴是将中药煎煮后加入浴水，通过温热、水浴和草药成分共同作用于人体的一种外治方法。常见形式包括全身药浴、局部药浴和足浴。中医常根据个人体质和需要选择不同的药浴方案。"] },
    en: { name: "Herbal Bath", description: ["An herbal bath involves adding a prepared herbal decoction to warm bath water. The practice combines the effects of warmth, immersion and selected herbs. It may be used as a relaxing wellness practice and can be adapted as a full-body bath, local bath or herbal foot bath according to individual needs."] },
  },
  {
    id: "auricular",
    image: auricularImage,
    zh: { name: "耳穴", description: ["耳穴疗法是通过刺激耳廓上的特定区域和穴位来进行身体调理的传统方法。常见方式包括耳穴按压、耳豆贴压等。中医认为耳部与人体经络及脏腑之间存在密切联系，因此可以通过耳部刺激辅助整体调理。"] },
    en: { name: "Auricular Therapy", description: ["Auricular therapy is a traditional Chinese medicine approach that stimulates specific points or areas of the external ear. Common techniques include gentle acupressure and the application of small seeds or beads to selected auricular points. In traditional Chinese medicine, the ear is considered to have connections with different areas and functions of the body, allowing auricular stimulation to be used as part of a holistic approach to wellbeing."] },
  },
  {
    id: "aromatherapy",
    image: aromatherapyImage,
    zh: {
      name: "芳香疗法与传统香事",
      description: [
        "芳香疗法与传统香事是中医外治和传统养生文化中具有特色的一类方法，主要通过植物芳香成分与嗅觉、呼吸以及体表接触等途径，为日常身心调养提供支持。",
        "现代芳疗主要使用精油、植物精萃等芳香植物成分，根据不同植物的芳香特性，通过嗅吸、扩香、按摩等方式应用于日常健康与身心放松。使用精油时需要注意适当稀释、使用剂量以及个人敏感性。",
        "中国传统香事则有着悠久的历史，包括香囊、香珠、香牌、佩香等形式。传统上，人们将芳香药材或植物材料配伍制成香囊、香珠或香牌，随身佩戴、悬挂或放置于生活环境中，使其芳香气息自然散发。不同的香方可以根据季节、环境、个人喜好以及传统香文化进行选择。",
        "香囊、香珠和香牌不仅具有传统养生文化意义，也融合了中药、香文化、手工艺术和生活美学，是中国传统“芳香养生”的重要表现形式。",
      ],
      highlights: [
        { title: "现代精油芳疗", description: "精油、植物芳香成分、嗅吸、扩香、芳香按摩等。" },
        { title: "传统香囊", description: "将芳香植物和传统香材配伍制成香囊，可佩戴、悬挂或放置于生活空间。" },
        { title: "香珠与香牌", description: "将传统香材制作成香珠、香牌等便携形式，使传统香文化融入现代生活。" },
      ],
    },
    en: {
      name: "Aromatherapy & Traditional Fragrance Practices",
      description: [
        "Aromatherapy and traditional fragrance practices represent a distinctive area of Chinese medicine–informed wellness and traditional health culture. They use aromatic plant materials and fragrances through inhalation, environmental diffusion, topical application or personal wearing as part of everyday wellbeing practices.",
        "Modern essential oil aromatherapy commonly uses essential oils and aromatic plant extracts. Depending on the characteristics of each botanical, they may be used through inhalation, diffusion, massage or appropriately diluted topical application to support relaxation and everyday wellbeing. Safe dilution, appropriate dosage and individual sensitivities should always be considered when using essential oils.",
        "Traditional Chinese fragrance practices have a long history and include herbal sachets (Xiang Nang), aromatic beads (Xiang Zhu), fragrance pendants or plaques (Xiang Pai), and personal fragrance wearing. Traditionally, aromatic herbs and plant materials are blended into carefully prepared fragrance formulas and placed in sachets, beads or pendants that can be worn, carried or displayed in living spaces.",
        "These practices allow the natural fragrance of aromatic materials to accompany everyday life. Different traditional fragrance formulas may be selected according to seasonal traditions, environmental conditions, personal preferences and the principles of traditional Chinese fragrance culture.",
        "Beyond their aromatic qualities, herbal sachets, aromatic beads and fragrance pendants also represent an integration of traditional Chinese medicine, fragrance culture, craftsmanship and lifestyle aesthetics. They provide a unique way of bringing traditional aromatic wellness practices into contemporary daily life.",
      ],
      highlights: [
        { title: "Modern Essential Oil Aromatherapy", description: "Essential oils, aromatic plant ingredients, inhalation, diffusion and aromatic massage." },
        { title: "Traditional Herbal Sachets", description: "Aromatic plants and traditional fragrance materials are blended into sachets that can be worn, hung or placed in living spaces." },
        { title: "Aromatic Beads & Fragrance Pendants", description: "Traditional fragrance materials are made into portable beads and pendants, bringing fragrance culture into contemporary life." },
      ],
    },
  },
  {
    id: "movement",
    image: movementImage,
    zh: { name: "练功", description: ["中医养生练功包括八段锦、太极、站桩、导引等传统身心练习。通过呼吸、动作、姿势和意识的协调，帮助改善身体活动能力、呼吸状态和身心放松。练功强调循序渐进、顺应个人体质和身体状况。"] },
    en: { name: "Traditional Health Practices & Movement", description: ["Traditional Chinese health practices include exercises such as Baduanjin, Tai Chi, standing meditation (Zhan Zhuang) and Dao Yin. These practices coordinate movement, posture, breathing and mental awareness to support physical mobility, relaxation and mind–body balance. They are generally practised progressively and adapted to individual abilities and physical condition."] },
  },
  {
    id: "dietary-therapy",
    image: dietaryTherapyImage,
    zh: { name: "食疗", description: ["食疗是中医养生的重要组成部分，强调根据季节、体质、年龄、生活方式等因素选择适宜的食物和饮食方式。它并不是简单的“忌口”，而是通过日常饮食的长期调整来维护身体平衡，体现“药食同源”和“治未病”的理念。"] },
    en: { name: "Chinese Dietary Therapy", description: ["Chinese dietary therapy is an important part of traditional Chinese health preservation. It considers factors such as individual constitution, season, age, lifestyle and dietary habits when selecting appropriate foods and eating patterns. Rather than focusing simply on restriction, it emphasises sustainable dietary choices that support balance and wellbeing. It reflects the traditional concepts of “food and medicine sharing common origins” and preventive health care."] },
  },
];
